# Generated by Django 3.2.9 on 2021-11-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20211128_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=True),
        ),
    ]
